# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reacher22.github.io/"

# User settings
username: reacher22
user_description: I'm a Software Engineer.
user_title: Software Engineer
email: thd7830@naver.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username: murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules"]
